name: supabase_auth_client
description: Supabase authentication client wrapper for the VGV boilerplate.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
